# Generated by Django 4.2.1 on 2023-07-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_completedquiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquiz',
            name='seed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
