# Generated by Django 4.2.1 on 2023-07-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_completedquiz_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquiz',
            name='quiz',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
