# Generated by Django 4.2.1 on 2023-07-15 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprofile_friends_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
