# Generated by Django 4.2.1 on 2023-07-17 15:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_email_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank='True', null=True, upload_to=api.models.upload_to),
        ),
    ]
