# Generated by Django 4.2.1 on 2023-07-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquiz',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
